dev: mvp server-client
unbeman/ya-prac-go-second-grade pull request #1
Opened 2023-09-07 20:21 UTC by unbeman

Описание чуть позже будет в ридми

2023-09-11 21:02 UTC, tmvrus requested changes
необходимо выполнить формальные требования
<img width="735" alt="image" src="https://github.com/unbeman/ya-prac-go-second-grade/assets/554425/b023d82c-6b40-4867-9298-b5ce88e03463">

2023-09-13 14:17 UTC, unbeman commented
Добавила тестов
В ридми отображается бейдж с процентом покрытия

2023-09-13 20:21 UTC, tmvrus requested changes
работа безусловно интересная, точно с самым крутым readme

но принять ее я не могу, потому что не могу запустить для проверки, сервис считает что:
- у меня есть postgresql
- он на дефолтном порту
- там есть нужная сервису роль

но ничего из этого у меня нет, как и инструкции это все запустить

2023-09-13 20:21 UTC, tmvrus commented on internal/client/service/auth.go
> +		err = fmt.Errorf("%w : %s", ErrInternal, err)
такое использование fmt.Errorf допустимо, но не вполне корректно кмк, в данном случае контекст оригинально ошибки err подменяется на ErrInternal и все ф-и пакета errors будут работать именно с ErrInternal.

если хочется сообщить читателю кода, что нам действительно все равно на контекст ошибки, думаю, лучше привести ее к строке явно:
`fmt.Errorf("%w : %s", ErrInternal, err.Error())`

2023-09-13 20:21 UTC, tmvrus commented on internal/client/service/auth.go
> +		err = fmt.Errorf("%w : %s", ErrInternal, err)
или сделать что-то типа errors.Join если обе ошибки важны

2023-09-13 20:21 UTC, tmvrus commented on internal/client/model/credential_type.go
> +	*st = CredentialType(value.(string))
лучше приучить себя всегда проверять результат type assert тем более там где можно вернуть ошибку

2023-09-13 20:21 UTC, tmvrus commented on internal/server/database/pg.go
> +	batchSize int
эта переменная не используется

2023-09-13 20:21 UTC, tmvrus commented on internal/server/app.go
> +	a.server.Close()
Close() зачем-то может вернуть ошибку, которая никогда внутри Close() не случается

2023-09-13 20:21 UTC, tmvrus commented on internal/server/model/credential.go
> +}
остались еще сущности без документации

2023-09-13 20:21 UTC, tmvrus commented on internal/server/transport/interceptor.go
> +func newServerStreamWrapper(ss grpc.ServerStream, newCtx context.Context) *serverStreamWrapper {
не нашел где это вызывается

2023-09-13 20:21 UTC, tmvrus commented on cmd/server/main.go
> +	}
обычно для такого используют Fatal

2023-09-14 11:31 UTC, unbeman commented on internal/server/transport/interceptor.go
> +func newServerStreamWrapper(ss grpc.ServerStream, newCtx context.Context) *serverStreamWrapper {
убрала неиспользуемый код

2023-09-14 12:45 UTC, unbeman commented
@tmvrus 
- Поправила код с учетом замечаний
- Добавила описание запуска клиента и сервера в ридми

2023-09-14 16:19 UTC, tmvrus approved these changes
Есть инструкция по запуску, но нет инструкции по остановке )
Очень хорошая работа.

2023-09-14 16:19 UTC, tmvrus commented on internal/server/services/sync_test.go
> +		t.Run(tt.name, func(t *testing.T) {
сабтесты частенько запускают параллельно, если так сделать - такой код работать перестанет
https://go.dev/play/p/Blw5OzcF-Ih

2023-09-14 16:19 UTC, tmvrus commented on internal/server/services/sync_test.go
> +			defer ctrl.Finish()
для моков полезнее использовать аналог 
t.Cleanup(ctrl.Finish)
он покажет ошибки до завершения теста

2023-09-14 16:19 UTC, tmvrus commented on internal/server/services/sync_test.go
> +				return
ни на что не влияет

2023-09-14 17:09 UTC, unbeman commented
@tmvrus Спасибо за ревью и аппрув!

Чуть позже вернусь к проекту, хочу таки доделать то, что было в планах, но не успевалось к дедлайнам.

2023-09-18 18:10 UTC, merged